version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: eventstore/eventstore:20.10.2-buster-slim
        environment:
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_RUN_PROJECTIONS: All
          EVENTSTORE_START_STANDARD_PROJECTIONS: 1
          EVENTSTORE_EXT_TCP_PORT: 1113
          EVENTSTORE_HTTP_PORT: 2113
          EVENTSTORE_INSECURE: 1
          EVENTSTORE_ENABLE_EXTERNAL_TCP: 1
          EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 1
      - image: 'circleci/mongo:latest'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
      
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            dpkg -i packages-microsoft-prod.deb
            apt-get update -y && apt-get upgrade -y
            apt-get install gnupg2 -y
            apt-get install -y dotnet-sdk-3.1

      - run:
          name: Build solution
          command: |
            dotnet restore
            dotnet build --no-restore -c DebugOnPremise 

      - azure-cli/install

      - run:
          name: Test
          command: |
            az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            dotnet test -c DebugOnPremise 