version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
      
    steps:
      - checkout

      - azure-cli/install

      - run:
          name: Build solution
          command: dotnet build

      - run:
          name: Test
          command: |
            az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            dotnet test