version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
      - image: eventstore/eventstore
        command: [--enable-external-tcp, --ext-ip=0.0.0.0, --int-ip=0.0.0.0, --insecure]
        environment:
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_INT_TCP_PORT: 1112
          EVENTSTORE_EXT_TCP_PORT: 1113
          EVENTSTORE_INT_HTTP_PORT: 2112
          EVENTSTORE_EXT_HTTP_PORT: 2113
      - image: 'circleci/mongo:latest'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
      
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get upgrade -y
            apt-get install gnupg2

      - azure-cli/install

      - run:
          name: Build solution
          command: dotnet build

      - run:
          name: Test
          command: |
            az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            dotnet test